### ISSUE TITLE
Glances API

### ISSUE THREAD

**Issue by Amir974** [Thibauth/python-pushover#18]
Any plans to support the new glances API ?

**Comment by Thibauth** [comment]
I hadn't heard of this new glances API, but I have just looked at it and adding support for it should be rather straightforward. Would you be interested in implementing it?

**Comment by Amir974** [comment]
I already have a working implementation more or less...
but I don't have the dev environment setup and I my programming skills are a bit limited :)

I wrote it as a custom component based on the original pushover - homeassisstant implementation adapted to this new API.
it does the short message & a numeric message pushed directly to the watch face complication where setup...

I'll upload my code to github once I have a chance to clean it up, but I guess it will take some work and testing before it can go in as an official component... would appreciate the help!

**Comment by chevell** [comment]
I've opened a PR for this: https://github.com/Thibauth/python-pushover/pull/19

**Comment by Thibauth** [comment]
Thanks so much! I am really busy this week so can't look at it in details, but will do as soon as possible next week and hopefully will merge it then.

**Comment by chevell** [comment]
@Thibauth No worries, let me know if you have any questions.

Cheers,

Dave

**Comment by Thibauth** [comment]
#19 has been merged and I just released a new version (0.3) containing the addition. Thanks to both of you!
