### ISSUE TITLE
request to add expire parameter to command line pushover

### ISSUE THREAD

**Issue by mhaeberli** [Thibauth/python-pushover#20]
Thanks for the pushover python etc interface!

Since priority can be set to 2, where expire value must be set (according to error message), it would be good to add an expire argument to the command line interface.

I may make an attempt at this and subbmit a pull request ...

**Comment by Thibauth** [comment]
Thanks! I agree that it would be useful to have an optional "expire" argument to the command line interface. I will gladly accept a pull request for this, if you submit one. Otherwise, I might have time to work on it a bit later (maybe towards the end of next week).

**Comment by mhaeberli** [comment]
Thibaut,
Thank you!
If I get to it first, I'll send a pull request.
Merçi Biens
Martin
--
Post Script : - one thought I had was, IF priority == 2, THEN set a default
expire, say, to 120, unless expire already passed in as a value on command
line.

**Comment by copart** [comment]
mhaeberli , 
I sent in a pull request for this.  It appears you also need retries set as well.

**Comment by mhaeberli** [comment]
thx

**Comment by Thibauth** [comment]
Sorry for the long delay! This was solved nicely by @copart pull request #22 and will be included in the next release. If you want to update your local version with this fix, you should run something like:

    pip install --upgrade git+https://github.com/Thibauth/python-pushover
