### ISSUE TITLE
Could you do a release with the image attachments?

### ISSUE THREAD

**Issue by rwifall** [Thibauth/python-pushover#25]
A new release that includes the image attachments functionality would be useful.

**Comment by brandonscript** [comment]
Would love some documentation on how to use it too - took me a while to figure out I needed to do `attachment = ("image.jpg", open(img, "rb"), "image/jpeg")` instead of just passing a file path.

**Comment by brandonscript** [comment]
Bump...

**Comment by chevell** [comment]
@brandonscript the simple way to use it would be like so:

```python
messenger = pushover.Client(PUSHOVER_USER_KEY, api_token=PUSHOVER_API_TOKEN)

with open('/path/to/my/image.png', 'rb') as image:
    messenger.send_message('Test message with image', attachment=image)
```

**Comment by brkr19** [comment]
Hi, would it be possible to include this functionality into a 0.4 release?  I see the functionality was added in pull #24, but I don't see it bundled as a release.  I'm working on some changes for the Home Assistant project that could greatly benefit from this functionality.  I'd be happy to help if there's anything that's needed.  Thanks!

**Comment by chevell** [comment]
@Thibauth let me know if I can help in a more general fashion with this project, if there is basic maintenance / release work I can do, or if I can help with automating deployment of new releases etc.

**Comment by Thibauth** [comment]
I just did a new release (0.4) with the attachment feature. Thanks again for the help and sorry for the delay. Please let me know if anything is broken.

@chevell I would be happy to give you access to the repository if you think you could help with general maintenance.

**Comment by rwifall** [comment]
Thanks
